@manifestUrl = https://1u31fuekv5.execute-api.eu-west-1.amazonaws.com/prod/manifest/
@hostname = {{$dotenv HOSTNAME}}
@userName = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

###
# @name Manifest
GET {{manifestUrl}}?hostname={{hostname}} HTTP/1.1

###
# @name MetadataManifest
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/metadata/manifest HTTP/1.1

###
# @name AuthLogin
POST {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/auth/login HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Content-Type: application/json;charset=utf-8

{
    "userName": "{{userName}}",
    "password": "{{password}}"
}

###
# @name AuthGetConsentDocument
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/auth/get-consent-document HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Content-Type: application/json;charset=utf-8

###
# @name AuthDownloadConsentDocument
GET {{AuthGetConsentDocument.response.body.$.url}} HTTP/1.1

###
# @name AuthRefresh
POST {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/auth/refresh HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Content-Type: application/json;charset=utf-8

{
    "refreshToken": "{{AuthLogin.response.body.$.credentials.refreshToken}}",
}

###
# @name UserList
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/users HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name UserListWithAllAttributes
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/users?attributes=userName,firstName,lastName,email,phone,locale,company,address,zip,country,roleName,domainName,data,roles,termsAgreed,dateTermsAgreed,termsVersion,createdAt,enabled HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name UserGetWhoami
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/user?attributes=userName,firstName,lastName,email,phone,locale,company,address,zip,country,roleName,domainName,data,roles HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name UserGetAuthUser
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/users/{{AuthLogin.response.body.$.user.userName}}?attributes=firstName,lastName,email,phone,locale,company,address,zip,city,country,roleName,domainName,notes1,notes2,notes3,data,roles,termsAgreed,dateTermsAgreed,termsVersion,createdAt,enabled HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name DomainList
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/domains HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name DomainListTopDomains
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/domains/list HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name DomainListSubdomains
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/domains/{{AuthLogin.response.body.$.user.domainName}}/list HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name DomainGet
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/domains/{{AuthLogin.response.body.$.user.domainName}} HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name FileV2List
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/files?listAll=true HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name ThingTypeList
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/thingtypes HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}

###
# @name ThingTypeGet
GET {{Manifest.response.body.$.ApiGatewayRootUrl}}/{{Manifest.response.body.$.StackName}}/thingtypes/{{ThingTypeList.response.body.$[0].id}} HTTP/1.1
x-api-key: {{MetadataManifest.response.body.$.ApiKey}}
Authorization: Bearer {{AuthLogin.response.body.$.credentials.token}}
